[devshell]
name = "hugo website"

[[commands]]
package = "hugo"

[[commands]]
package = "go"

[[commands]]
command = "hugo server"
name = "server"
help = "Server"

[[commands]]
command = "hugo server --buildDrafts"
name = "drafts"
help = "Server including drafts"

[[commands]]
command = "hugo"
name = "build"
help = "Build site – usually not necessary"
