baseURL = 'https://jankremer.eu/'
languageCode = 'de'
title = 'Jan Kremer'
copyright = 'CC-BY-SA 4.0'

[markup]
[markup.highlight]
style = "rose-pine-dawn"

[params]
[params.author]
name = 'Jan Kremer'
email = 'mail@jankremer.eu'

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[[menus.main]]
name = 'Microblog'
pageRef = '/micro'
weight = 30

[[menus.main]]
name = 'Fotos'
pageRef = '/photos'
weight = 40

[[menus.main]]
name = 'Über mich'
pageRef = '/about'
weight = 50
